apiVersion: apps/v1
kind: Deployment
metadata:
  name: appforkubernetes-deployment
  labels:
  app: appforkubernetes
spec:
  replicas: 3
  template:
    metadata:
      labels:
      app: appforkubernetes
    spec:
      containers:
        - name: b5ce375c3b23
          image: kubernetesclustercomputer/kubernetesprivate_repo:tag1
          ports:
          - containerPort: 8080
            protocol: TCP
           resources:
             requests:
            cpu: 100m
            memory: 100Mi
            limits:
            cpu: 500m
            memory: 2500Mi
