apiVersion: apps/v1
kind: Deployment
metadata:
  name: appforkubernetes-deployment
  labels:
  app: appforkubernetes
spec:
  replicas: 3
  selector:
    matchLabels:
    app: appforkubernetes
  template:
    metadata:
      labels:
      app: appforkubernetes
    spec:
      containers:
        name: appforkubernetes
          image: b5ce375c3b23:tag01
          ports:
           containerPort: 80
